language: minimal
dist: xenial
env:
  IMAGE=ci-sample
  TAG=travis
script:
- docker build -t $DOCKER_USERNAME/$IMAGE:$TAG .
after_success:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
    docker push $DOCKER_USERNAME/$IMAGE:$TAG;
  fi
notifications:
  slack:
    secure: Hbtcaoa3QgNRy6dfOIUZUFM5fP5yioGVAXRduLII6PTu7u6x5abMPs1UQP1heV1G10e0B9I/5UVzdxLaJk9y7HrDhTr5mSg5MZ2YyMFpfq86AmO4Vi3ZKDV1l18w4/n0cVBHKKkHBq10MeiHP3Kf/c2y+AtB/FfEVk7PnZQOh79DYx1yo1LooDloklYlAb3p3e9UklLeNtzin72fzjiHMQbDO3JPxUYfJf20mYVHlwaJVHXouC+RzE/h8GsDhq+r6HfUF4Rjn61Vsi1DToG0Tr9zo+JL+tnQ9RFHZ/I0bKzmuJhx6n+Tw/NTpsfJ2J17AwROmniuehNFr/HLDHpPbwFpX+PRZizJIQcHxi4J8im0RwiFMsghuHhp4DCvCcHjsVdR0XR8HjuP+SW4HIi0PUjlIgcfGD5G36H5XRZM4YBqDhTM97rkmqCb0c7hHvP71WGKz3SSccm0y57dlOPTPwHAa8t2fRozdjNPGR6/aEqJr6skXSBnm7qXCa9Xs6+eTLmATlyhQj09Q8mgW8YaON1dhh7AT588n3d8/T3afFWAroKCElQd7Ye8oPAH0RAdimjbwZ7oj9qtWjMMpsap9km3rhbnYlx5/yavfmw/nUOrHfkYfho4ZE9mZ1Ys9HZETMv4Je4JQJ3KtqU24tDG67bIqzBxqaq7RBsqOa5tJas=
